//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_final_barberia.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class deudores
    {
        public string cod_deudor { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono_fijo { get; set; }
        public Nullable<int> celular { get; set; }
        public Nullable<int> documento { get; set; }
        public Nullable<int> cantidad_que_debe { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
